### ISSUE TITLE
User-Agentを指定できるようにするべき(？)

### ISSUE THREAD

**Issue by ghost** [yyoshiki41/go-radiko#4]
[議論]
タイトル通りで、UAを指定できるようにするべきではないでしょうか？

例えば、yyoshiki41/radigoでは"radigo"と指定することでradiko運営への認知が行えます

現在radikoがAPIを公式に公開しているわけではないので、利用するにあたってUAをきちんと設定することには意義があると思いますがいかかでしょうか？

よろしくお願いします

**Comment by yyoshiki41** [comment]
> タイトル通りで、UAを指定できるようにするべきではないでしょうか？

そうですね、
ありがとうございます！

下記で対応いたしました。
https://github.com/yyoshiki41/go-radiko/commit/6f369ca4feddaac58908f0af431fe50c06aedc72
